services:
  elm-dev:
    build: .
    container_name: particulas
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    volumes:
      - .:/app
      - /app/node_modules  # Evita sobrescribir node_modules del contenedor
    ports:
      - "8000:8000"
    command: ["elm-live", "src/Main.elm", "--open", "--pushstate", "--start-page=index.html", "--host=0.0.0.0", "--", "--output=main.min.js" ]
    